apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: veriff-ios-spm
  description: ''
  annotations:
    veriff.com/criticality: none
    github.com/project-slug: Veriff/veriff-ios-spm
  tags:
  - swift
spec:
  type: undefined
  owner: undefined
  lifecycle: undefined
